### ISSUE TITLE
Step forward

### ISSUE THREAD

**Issue by m0t0r** [Semantic-Org/Semantic-UI-Angular#14]
Hey guys, I hope I will get more free time soon and get back to this project. I wanna know what do you think we should choose as a _step forward_ for the project.

Well, I am talking about tree options:
* We just upgrade up to _**angular 1.4**_, as a big part of which is a new API for animations.
* We're taking step 1 and adding _**ES6**_ with its sweet features.
* We're moving even more further and considering to use _**TypeScript**_, with its power.

As the code base is really small at this moment but new tech is actively coming we probably need to discuss about plans for the future.

I'd vote for the _second option_.

Please, share your thoughts

**Comment by mxth** [comment]
I would go for TypeScript because of the type system. And it's supposed to be aligned with es6 anyway.

**Comment by RomainLanz** [comment]
I would also go for TypeScript. Btw, AngularJS 2 is going to be build with TypeScript.

**Comment by RomainLanz** [comment]
What do you think about merging directives from https://github.com/angularify/angular-semantic-ui (with permission)?

**Comment by m0t0r** [comment]
I think that we do not have plans to merge that project into the current one. @caitp, need your input here as well and also on the issue topic.

**Comment by m0t0r** [comment]
@stevesherrie's and @mxth's thoughts are required here as well

**Comment by m0t0r** [comment]
We are planing to move forward towards ES6

**Comment by caitp** [comment]
TypeScript's alignment with es6 is sort of questionable at this time (the lack of ClassExpression support makes unit testing a major pain). I would hold off on that until angular2 is a bit more stable and it looks worthwhile porting stuff to angular2.

As for ES6, browser support is a bit of an issue, although we are steadily working to improve this. 1.x angular apps may need to support earlier browsers than Chrome 46 or MS Edge though.

**Comment by m0t0r** [comment]
@caitp it was assumed to have code base in ES6 and transpile it down to ES5 for the browsers support. I really do not see actual reasons to sticky with ES5 still (as the code base is pretty small) when we can prepare code to be compatible with older browsers and look to the future when there not going to be a need to transpile anything.

**Comment by caitp** [comment]
Yeah I'd rather not do that just because it doesn't really gain anything, and the dev ops just aren't worth it

**Comment by RomainLanz** [comment]
Note that if we follow ES6 (ES7 also?) we can use these components easily on http://aurelia.io/ too.

**Comment by kowsheek** [comment]
Hey peoples. I've become involved with a project that's using Semantic and AngularJS so I can actively contribute to this project moving forward.

I vote for Angular 1.4 update with ES6 features.

I would also like to hear what our goals are and milestones we can set up to achieve.

Cheers!

**Comment by matheuspoleza** [comment]
I'm thinking in some like: https://github.com/AngularClass/NG6-starter

**Comment by matheuspoleza** [comment]
What we have to do to move things forward?
ES6 features will solve all problems?

**Comment by matheuspoleza** [comment]
closing all issues and PR for a while. Restarting project roadmap
