### ISSUE TITLE
Checkbox work only once

### ISSUE THREAD

**Issue by RomainLanz** [Semantic-Org/Semantic-UI-Angular#24]
Hi everyone,

I have got a weird problem with Safari, Firefox and Chrome about checkboxes.

They work but I can only see one time the tick.

Example:
* [x] Checkbox // Click -> $scope.checked = false;
* [ ] Checkbox // Click -> $scope.checked = true;
* [ ] Checkbox // Click -> $scope.checked = false;
* [ ] Checkbox // Click -> $scope.checked = true;
* etc.

I have take a look in the source code, all seems fine. I have also watch the element to see any modifications. Value of the element is correct, when `$scope.checked = true` the element has `checked="checked"`.

Have you any ideas?

Thanks.

**Comment by stevesherrie** [comment]
@RomainLanz Can you post your exact markup? I can't reproduce it offhand.

**Comment by RomainLanz** [comment]
Sure.

So this is one of my checkbox:
```html
<div class="field">
    <sm-checkbox ng-model="vm.newPressRelease.publishOnHome">Home page</sm-checkbox>
</div>
```

It's mapped on a simple blank object
```javascript
vm.newPressRelease = {};
```

When checkboxes are already checked, I can uncheck them, but can't check them again (visualy).

**Comment by m0t0r** [comment]
@stevesherrie, any updates in here ?

**Comment by stevesherrie** [comment]
@m0t0r Oh yeah I stalled on this. Let me check it out now.

**Comment by stevesherrie** [comment]
@RomainLanz I can't reproduce with your snippets. Can you share a more complete example? A CodePen maybe?

**Comment by asubota** [comment]
Hi all!
I faced with the same problem. This [PR](https://github.com/Semantic-Org/Semantic-UI-Angular/pull/28/files) should fix it. It worked for me.

**Comment by m0t0r** [comment]
Thanks, @asubota
