### ISSUE TITLE
Semantic UI for Angular 2

### ISSUE THREAD

**Issue by ansarizafar** [Semantic-Org/Semantic-UI-Angular#49]
Please consider creating  Angular 2 components for amazing Semantic UI modules without Jquery dependency.

**Comment by matheuspoleza** [comment]
Hello, @ansarizafar 

We are working to change the structure of the project and migrate to 1.4 with angular typescript. After that we already have plans to migrate to angular 2.

Thanks for the suggestion, it is a very important point.

**Comment by leshin** [comment]
+1

**Comment by ColinFrick** [comment]
+1

**Comment by evanplaice** [comment]
@matheuspoleza Ping me when you start the on Angular2. I may be able to help.

**Comment by m0t0r** [comment]
We're going to focus on angular 1 for now, once angular 2 will get animations support we will be working on angular 2 components.
