### ISSUE TITLE
Have some directive in javascript, interested?

### ISSUE THREAD

**Issue by PD75** [Semantic-Org/Semantic-UI-Angular#58]
I wrote directives for modal, pop-up and dropdown. Is there an interest that I up-load them?

I did not find any clear rules in #8 but I noticed that what I have is very different from what is here already.

**my approach:**
Since there was nothing really working available I took a very simple approach:
- Using semantic-ui's native java script
- Minimum logic, basically passing through all settings and behaviors to semantic-ui's java scripts
- Almost no manipulation of CSS classes from of directive, I think semantic-ui looks really good as it is and matches angular nicely

**Comment by PD75** [comment]
No response, closing issue

**Comment by m0t0r** [comment]
hey @PD75, sorry but we din't have activity for sometime here. Thank you for your offer but the goal of this project is to create native AngularJS components for Semantic-UI. We don't use Semantic-UI JS and we also use TypeScript as a language.
