### ISSUE TITLE
Angular2 directives completed!

### ISSUE THREAD

**Issue by allenJynRoyston** [Semantic-Org/Semantic-UI-Angular#64]
Hi everybody, I finished a set of Angular2 directives.  I was hoping you could link to the main site?

http://www.semanticui-ang2.com/

**Comment by erslater** [comment]
@allenRoyston Its great to see some work being done on this and I thank you for the work you did.  I think for it to be successful people need to see work being done on it on a regular basis which means getting help.  

I suggest you post this on the main semantic ui issues board to raise awareness in an attempt to get others involved.  Without traction in usage it is likely to run into the same fate as the libraries posted previously where the initial work was done and nothing followed for months.

I hope we can all jump on the bandwagon and make this work!

**Comment by allenJynRoyston** [comment]
Hey thanks for the reply!  I would love to get some help on this as you suggested so any advice is useful.  Where is the main issue suggestion board you mentioned?

Otherwise, I'm trying to get the site indexed and keep it up to date with the latest Angular 2 versions.  Damn framework keeps changing ever so slightly so I have to update the source code each time it does.  BUT after the site starts showing up on Google and Angular 2 is more stable I'll return to work on it.

Thanks again for the reply!

**Comment by erslater** [comment]
@allenRoyston The main issues board is at https://github.com/Semantic-Org/Semantic-UI/issues

**Comment by matheuspoleza** [comment]
@allenRoyston thank you, as mentioned before please post this issue in the board suggested :)

**Comment by erslater** [comment]
@matheuspoleza I dont think this should be closed out.  People need the ability to see this and start contributing since semantic is not doing anything on this.  Perhaps it can be pushed as the semantic solution as opposed to waiting for an official solution.
