### ISSUE TITLE
modal directive?

### ISSUE THREAD

**Issue by micha-LEAP** [Semantic-Org/Semantic-UI-Angular#7]
I am wanting to use semantic's modal module in a way similar to the AngularUI-bootstrap modal directive. Unfortunately my Angular-foo is not yet strong enough to write it myself. Is anyone working on more directives for semantic-ui and angular?

**Comment by m0t0r** [comment]
@micha-LEAP, I own this project so far. I will try to ship a solution for modal directive as soon as I can.

**Comment by RomainLanz** [comment]
Any news on this @m0t0r?

Also https://github.com/Semantic-Org/Semantic-UI-Angular/issues/23

**Comment by m0t0r** [comment]
@RomainLanz not much, but will return to this issue as soon as I can. If you are willing to create this directive we are happy with that :+1:

**Comment by matheuspoleza** [comment]
@m0t0r I'm interested to start work on it. Can I?

**Comment by m0t0r** [comment]
@matheuspoleza, can you ping me on gitter ?

**Comment by matheuspoleza** [comment]
@m0t0r of course

**Comment by matheuspoleza** [comment]
closing all issues and PR for a while. Restarting project roadmap

**Comment by dv336699** [comment]
also looking for the modal directive, which is why I'm still tied to angular-ui-bootstrap.
I'm glad to contribute.
